CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    data_expiracao DATE,
    dias_acesso INTEGER
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    usuario_id BIGINT,
    CONSTRAINT uk_categoria_nome_usuario UNIQUE (nome, usuario_id)
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    preco DECIMAL(19, 2) NOT NULL,
    quantidade_stock DECIMAL(19, 3) NOT NULL,
    stock_minimo DECIMAL(19, 3),
    unidade VARCHAR(50),
    codigo_barras VARCHAR(100),
    usuario_id BIGINT,
    categoria_id BIGINT,
    CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);

CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda DATE NOT NULL,
    quantidade DECIMAL(19, 3) NOT NULL,
    preco_unitario DECIMAL(19, 2) NOT NULL,
    total DECIMAL(19, 2) NOT NULL,
    observacao VARCHAR(255),
    produto_id BIGINT NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT fk_venda_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

CREATE TABLE devedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    divida DECIMAL(19, 2) NOT NULL,
    descricao VARCHAR(255),
    data DATE,
    usuario_id BIGINT
);
