-- =============================================================
-- V7: Identificador da venda, métodos de pagamento e descontos
-- H2 Database
-- =============================================================

-- 1. Identificador de venda no aparelho (uuid_cliente)
ALTER TABLE vendas ADD COLUMN uuid_cliente VARCHAR(100);
CREATE UNIQUE INDEX uk_vendas_usuario_uuid_cliente ON vendas(usuario_id, uuid_cliente);

-- 2. Tabela metodos_pagamento
CREATE TABLE metodos_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(50) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE NOT NULL,
    ordem INT DEFAULT 0 NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_metodo_tipo CHECK (tipo IN ('DINHEIRO', 'DIGITAL', 'FIADO')),
    CONSTRAINT uk_metodos_usuario_nome UNIQUE (usuario_id, nome),
    CONSTRAINT fk_metodos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE INDEX idx_metodos_pagamento_usuario ON metodos_pagamento(usuario_id, ordem);

-- 3. Inserir métodos padrão para todos os utilizadores existentes
INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'Dinheiro', 'DINHEIRO', true, 1 FROM usuarios u;

INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'M-Pesa', 'DIGITAL', true, 2 FROM usuarios u;

INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'e-Mola', 'DIGITAL', true, 3 FROM usuarios u;

INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'A fiado', 'FIADO', true, 4 FROM usuarios u;

INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'mKesh', 'DIGITAL', false, 5 FROM usuarios u;

INSERT INTO metodos_pagamento (usuario_id, nome, tipo, ativo, ordem)
SELECT u.id, 'Cartão', 'DIGITAL', false, 6 FROM usuarios u;

-- 4. Actualizar pagamentos_venda com metodo_id e referencia
ALTER TABLE pagamentos_venda ADD COLUMN metodo_id BIGINT;
ALTER TABLE pagamentos_venda ADD COLUMN referencia VARCHAR(100);

UPDATE pagamentos_venda pv
SET metodo_id = (
    SELECT mp.id FROM metodos_pagamento mp
    WHERE mp.usuario_id = pv.usuario_id
      AND (
        (pv.metodo = 'DINHEIRO' AND mp.nome = 'Dinheiro') OR
        (pv.metodo = 'MPESA' AND mp.nome = 'M-Pesa') OR
        (pv.metodo = 'EMOLA' AND mp.nome = 'e-Mola') OR
        (pv.metodo = 'MKESH' AND mp.nome = 'mKesh') OR
        (pv.metodo = 'CARTAO' AND mp.nome = 'Cartão') OR
        (pv.metodo = 'FIADO' AND mp.nome = 'A fiado')
      )
    LIMIT 1
);

ALTER TABLE pagamentos_venda ADD CONSTRAINT fk_pagamentos_venda_metodo 
    FOREIGN KEY (metodo_id) REFERENCES metodos_pagamento(id) ON DELETE RESTRICT;
CREATE INDEX idx_pagamentos_venda_metodo ON pagamentos_venda(metodo_id);
ALTER TABLE pagamentos_venda DROP CONSTRAINT IF EXISTS chk_pagamento_venda_metodo;

-- 5. Colunas de desconto e nota em venda_itens
ALTER TABLE venda_itens ADD COLUMN desconto_percentual NUMERIC(19, 2) DEFAULT 0 NOT NULL;
ALTER TABLE venda_itens ADD COLUMN desconto_valor NUMERIC(19, 2) DEFAULT 0 NOT NULL;
ALTER TABLE venda_itens ADD COLUMN preco_final NUMERIC(19, 2) DEFAULT 0 NOT NULL;
ALTER TABLE venda_itens ADD COLUMN nota VARCHAR(255);

UPDATE venda_itens SET preco_final = preco_unitario WHERE preco_final = 0;
