CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    data_expiracao DATE,
    dias_acesso INTEGER
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    usuario_id BIGINT,
    CONSTRAINT uk_categoria_nome_usuario UNIQUE (nome, usuario_id)
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    preco NUMERIC(19, 2) NOT NULL,
    quantidade_stock NUMERIC(19, 3) NOT NULL,
    stock_minimo NUMERIC(19, 3),
    unidade VARCHAR(50),
    codigo_barras VARCHAR(100),
    usuario_id BIGINT,
    categoria_id BIGINT REFERENCES categorias(id)
);

CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda DATE NOT NULL,
    quantidade NUMERIC(19, 3) NOT NULL,
    preco_unitario NUMERIC(19, 2) NOT NULL,
    total NUMERIC(19, 2) NOT NULL,
    observacao VARCHAR(255),
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    usuario_id BIGINT
);

CREATE TABLE devedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    divida NUMERIC(19, 2) NOT NULL,
    descricao VARCHAR(255),
    data DATE,
    usuario_id BIGINT
);
