import {
  Tag,
  ShoppingBag,
  Apple,
  CupSoda,
  SprayCan,
  Package,
  Wheat,
  Beef,
  Milk,
  Carrot,
  Coffee,
  BrushCleaning,
  Pill,
  Shirt,
  Footprints,
  Smartphone,
  Wrench,
  Lightbulb,
  Egg,
  Candy,
} from 'lucide-react';

export const categoryIcons = [
  { key: 'tag', label: 'Geral', icon: Tag },
  { key: 'bag', label: 'Compras', icon: ShoppingBag },
  { key: 'fruit', label: 'Fruta', icon: Apple },
  { key: 'drink', label: 'Bebidas', icon: CupSoda },
  { key: 'care', label: 'Higiene', icon: SprayCan },
  { key: 'box', label: 'Embalagens', icon: Package },
  { key: 'bread', label: 'Cereais', icon: Wheat },
  { key: 'meat', label: 'Carne', icon: Beef },
  { key: 'milk', label: 'Laticínios', icon: Milk },
  { key: 'vegetable', label: 'Legumes', icon: Carrot },
  { key: 'coffee', label: 'Café', icon: Coffee },
  { key: 'cleaning', label: 'Limpeza', icon: BrushCleaning },
  { key: 'health', label: 'Saúde', icon: Pill },
  { key: 'clothes', label: 'Roupa', icon: Shirt },
  { key: 'shoes', label: 'Calçado', icon: Footprints },
  { key: 'phone', label: 'Eletrónica', icon: Smartphone },
  { key: 'tools', label: 'Ferramentas', icon: Wrench },
  { key: 'light', label: 'Iluminação', icon: Lightbulb },
  { key: 'egg', label: 'Ovos', icon: Egg },
  { key: 'sweets', label: 'Doces', icon: Candy },
];

// Os valores antigos são apenas interpretados na apresentação, sem reescrever os registos.
const legacyIcons: Record<string, string> = {
  '🛍': 'bag',
  '🏷': 'tag',
  '🍎': 'fruit',
  '🥤': 'drink',
  '🧴': 'care',
  '📦': 'box',
  '🍞': 'bread',
  '🥩': 'meat',
  '🧀': 'milk',
  '🥦': 'vegetable',
  '🍺': 'drink',
  '☕': 'coffee',
  '🧹': 'cleaning',
  '🪣': 'cleaning',
  '💊': 'health',
  '👕': 'clothes',
  '👟': 'shoes',
  '📱': 'phone',
  '🔧': 'tools',
  '💡': 'light',
  '🐔': 'meat',
  '🥚': 'egg',
  '🌽': 'vegetable',
  '🫙': 'box',
  '🧂': 'box',
  '🫒': 'vegetable',
  '🍫': 'sweets',
  '🍬': 'sweets',
};
export function categoryIconKey(value: string) {
  return legacyIcons[value.replace(/️/g, '')] || value || 'tag';
}
